// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0--rc1
// source: users.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TLSRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientPublicKey string                 `protobuf:"bytes,2,opt,name=client_public_key,json=clientPublicKey,proto3" json:"client_public_key,omitempty"`
	IsRegistring    bool                   `protobuf:"varint,3,opt,name=is_registring,json=isRegistring,proto3" json:"is_registring,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TLSRequest) Reset() {
	*x = TLSRequest{}
	mi := &file_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSRequest) ProtoMessage() {}

func (x *TLSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSRequest.ProtoReflect.Descriptor instead.
func (*TLSRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{0}
}

func (x *TLSRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TLSRequest) GetClientPublicKey() string {
	if x != nil {
		return x.ClientPublicKey
	}
	return ""
}

func (x *TLSRequest) GetIsRegistring() bool {
	if x != nil {
		return x.IsRegistring
	}
	return false
}

type TLSResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerPublicKey string                 `protobuf:"bytes,1,opt,name=server_public_key,json=serverPublicKey,proto3" json:"server_public_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TLSResponse) Reset() {
	*x = TLSResponse{}
	mi := &file_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSResponse) ProtoMessage() {}

func (x *TLSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSResponse.ProtoReflect.Descriptor instead.
func (*TLSResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{1}
}

func (x *TLSResponse) GetServerPublicKey() string {
	if x != nil {
		return x.ServerPublicKey
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Device        string                 `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type AddUserAvatarPathRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Login             string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	StorageAvatarPath string                 `protobuf:"bytes,2,opt,name=storage_avatar_path,json=storageAvatarPath,proto3" json:"storage_avatar_path,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddUserAvatarPathRequest) Reset() {
	*x = AddUserAvatarPathRequest{}
	mi := &file_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserAvatarPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserAvatarPathRequest) ProtoMessage() {}

func (x *AddUserAvatarPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserAvatarPathRequest.ProtoReflect.Descriptor instead.
func (*AddUserAvatarPathRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{4}
}

func (x *AddUserAvatarPathRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AddUserAvatarPathRequest) GetStorageAvatarPath() string {
	if x != nil {
		return x.StorageAvatarPath
	}
	return ""
}

type AddUserAvatarPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserAvatarPathResponse) Reset() {
	*x = AddUserAvatarPathResponse{}
	mi := &file_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserAvatarPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserAvatarPathResponse) ProtoMessage() {}

func (x *AddUserAvatarPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserAvatarPathResponse.ProtoReflect.Descriptor instead.
func (*AddUserAvatarPathResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{5}
}

type GetUserAvatarPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAvatarPathRequest) Reset() {
	*x = GetUserAvatarPathRequest{}
	mi := &file_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAvatarPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAvatarPathRequest) ProtoMessage() {}

func (x *GetUserAvatarPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAvatarPathRequest.ProtoReflect.Descriptor instead.
func (*GetUserAvatarPathRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserAvatarPathRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type GetUserAvatarPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoragePath   string                 `protobuf:"bytes,1,opt,name=storagePath,proto3" json:"storagePath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAvatarPathResponse) Reset() {
	*x = GetUserAvatarPathResponse{}
	mi := &file_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAvatarPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAvatarPathResponse) ProtoMessage() {}

func (x *GetUserAvatarPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAvatarPathResponse.ProtoReflect.Descriptor instead.
func (*GetUserAvatarPathResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserAvatarPathResponse) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{8}
}

func (x *AuthRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *AuthRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_users_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{9}
}

func (x *AuthResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AuthResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuthResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_users_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{10}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_users_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{11}
}

func (x *UserInfo) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_users_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{12}
}

func (x *SearchResponse) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetInfoByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoByIDRequest) Reset() {
	*x = GetInfoByIDRequest{}
	mi := &file_users_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoByIDRequest) ProtoMessage() {}

func (x *GetInfoByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoByIDRequest.ProtoReflect.Descriptor instead.
func (*GetInfoByIDRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{13}
}

func (x *GetInfoByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetInfoByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoByIDResponse) Reset() {
	*x = GetInfoByIDResponse{}
	mi := &file_users_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoByIDResponse) ProtoMessage() {}

func (x *GetInfoByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoByIDResponse.ProtoReflect.Descriptor instead.
func (*GetInfoByIDResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{14}
}

func (x *GetInfoByIDResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetInfoByIDResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_users_proto protoreflect.FileDescriptor

const file_users_proto_rawDesc = "" +
	"\n" +
	"\vusers.proto\x12\x05users\"m\n" +
	"\n" +
	"TLSRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11client_public_key\x18\x02 \x01(\tR\x0fclientPublicKey\x12#\n" +
	"\ris_registring\x18\x03 \x01(\bR\fisRegistring\"9\n" +
	"\vTLSResponse\x12*\n" +
	"\x11server_public_key\x18\x01 \x01(\tR\x0fserverPublicKey\"o\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x16\n" +
	"\x06device\x18\x04 \x01(\tR\x06device\"$\n" +
	"\x10RegisterResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"`\n" +
	"\x18AddUserAvatarPathRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12.\n" +
	"\x13storage_avatar_path\x18\x02 \x01(\tR\x11storageAvatarPath\"\x1b\n" +
	"\x19AddUserAvatarPathResponse\"0\n" +
	"\x18GetUserAvatarPathRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\"=\n" +
	"\x19GetUserAvatarPathResponse\x12 \n" +
	"\vstoragePath\x18\x01 \x01(\tR\vstoragePath\"W\n" +
	"\vAuthRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"V\n" +
	"\fAuthResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\"%\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"D\n" +
	"\bUserInfo\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\"7\n" +
	"\x0eSearchResponse\x12%\n" +
	"\x05users\x18\x01 \x03(\v2\x0f.users.UserInfoR\x05users\"$\n" +
	"\x12GetInfoByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"?\n" +
	"\x13GetInfoByIDResponse\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xd7\x03\n" +
	"\fUsersService\x12,\n" +
	"\x03TLS\x12\x11.users.TLSRequest\x1a\x12.users.TLSResponse\x12;\n" +
	"\bRegister\x12\x16.users.RegisterRequest\x1a\x17.users.RegisterResponse\x12V\n" +
	"\x11AddUserAvatarPath\x12\x1f.users.AddUserAvatarPathRequest\x1a .users.AddUserAvatarPathResponse\x12V\n" +
	"\x11GetUserAvatarPath\x12\x1f.users.GetUserAvatarPathRequest\x1a .users.GetUserAvatarPathResponse\x12/\n" +
	"\x04Auth\x12\x12.users.AuthRequest\x1a\x13.users.AuthResponse\x125\n" +
	"\x06Search\x12\x14.users.SearchRequest\x1a\x15.users.SearchResponse\x12D\n" +
	"\vGetInfoByID\x12\x19.users.GetInfoByIDRequest\x1a\x1a.users.GetInfoByIDResponseB\x03Z\x01.b\x06proto3"

var (
	file_users_proto_rawDescOnce sync.Once
	file_users_proto_rawDescData []byte
)

func file_users_proto_rawDescGZIP() []byte {
	file_users_proto_rawDescOnce.Do(func() {
		file_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)))
	})
	return file_users_proto_rawDescData
}

var file_users_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_users_proto_goTypes = []any{
	(*TLSRequest)(nil),                // 0: users.TLSRequest
	(*TLSResponse)(nil),               // 1: users.TLSResponse
	(*RegisterRequest)(nil),           // 2: users.RegisterRequest
	(*RegisterResponse)(nil),          // 3: users.RegisterResponse
	(*AddUserAvatarPathRequest)(nil),  // 4: users.AddUserAvatarPathRequest
	(*AddUserAvatarPathResponse)(nil), // 5: users.AddUserAvatarPathResponse
	(*GetUserAvatarPathRequest)(nil),  // 6: users.GetUserAvatarPathRequest
	(*GetUserAvatarPathResponse)(nil), // 7: users.GetUserAvatarPathResponse
	(*AuthRequest)(nil),               // 8: users.AuthRequest
	(*AuthResponse)(nil),              // 9: users.AuthResponse
	(*SearchRequest)(nil),             // 10: users.SearchRequest
	(*UserInfo)(nil),                  // 11: users.UserInfo
	(*SearchResponse)(nil),            // 12: users.SearchResponse
	(*GetInfoByIDRequest)(nil),        // 13: users.GetInfoByIDRequest
	(*GetInfoByIDResponse)(nil),       // 14: users.GetInfoByIDResponse
}
var file_users_proto_depIdxs = []int32{
	11, // 0: users.SearchResponse.users:type_name -> users.UserInfo
	0,  // 1: users.UsersService.TLS:input_type -> users.TLSRequest
	2,  // 2: users.UsersService.Register:input_type -> users.RegisterRequest
	4,  // 3: users.UsersService.AddUserAvatarPath:input_type -> users.AddUserAvatarPathRequest
	6,  // 4: users.UsersService.GetUserAvatarPath:input_type -> users.GetUserAvatarPathRequest
	8,  // 5: users.UsersService.Auth:input_type -> users.AuthRequest
	10, // 6: users.UsersService.Search:input_type -> users.SearchRequest
	13, // 7: users.UsersService.GetInfoByID:input_type -> users.GetInfoByIDRequest
	1,  // 8: users.UsersService.TLS:output_type -> users.TLSResponse
	3,  // 9: users.UsersService.Register:output_type -> users.RegisterResponse
	5,  // 10: users.UsersService.AddUserAvatarPath:output_type -> users.AddUserAvatarPathResponse
	7,  // 11: users.UsersService.GetUserAvatarPath:output_type -> users.GetUserAvatarPathResponse
	9,  // 12: users.UsersService.Auth:output_type -> users.AuthResponse
	12, // 13: users.UsersService.Search:output_type -> users.SearchResponse
	14, // 14: users.UsersService.GetInfoByID:output_type -> users.GetInfoByIDResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_users_proto_init() }
func file_users_proto_init() {
	if File_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_proto_goTypes,
		DependencyIndexes: file_users_proto_depIdxs,
		MessageInfos:      file_users_proto_msgTypes,
	}.Build()
	File_users_proto = out.File
	file_users_proto_goTypes = nil
	file_users_proto_depIdxs = nil
}
